Custom Decision Categories
pharmaR/riskassessment pull request #459
Opened 2023-03-15 14:34 UTC by Jeff-Thompson12

Addresses #276

2023-03-17 13:25 UTC, Jeff-Thompson12 commented
Alright. I moved the database specifications and decision categories to a configuration file `db-config.yml`.
![image](https://user-images.githubusercontent.com/85879620/225916839-1dbff2eb-380c-4e49-a0b2-48d159ad55b9.png)

This utilizes the built in `{golem}` configuration options. I have moved the database specifications out of the arguments for `run_app()`. The tests are currently failing because the database needs to be updated. I would like feedback before I do that.

2023-03-17 17:08 UTC, AARON-CLARK requested changes
Overall, this PR is 🔥 and the progress should be seriously celebrated. I do have some comments:

First, using a config file is the right thing to do, but it is also "scary-er" to some users steepens the barrier to entry FOR SOME. It's just another new thing they'll have to learn, so anything we can do to make it easier for them would be a win. As such, I think this PR necessitates augmenting the deployment documentation that is "in the works" via PR #450. After this PR is integrated, I'd like you to contribute a whole section dedicated to the config file not only sharing how to use it, but also background info on how config files work.

So, I know that this PR is still in draft mode, so I know it's still a work in progress, but when I started playing with this branch, I noticed a few things you may or may not have gotten around to yet:

(1) When I run as is, with the defaults. I noticed the decision rules for each category are automatically evenly distributed over the 0 - 1 spectrum - so in this case, split into thirds. And if I added one more category, I noticed it broke into fourths. Love that automation - makes the user's lives easier for sure... However, I did notice that the third slider was all red. Not sure why...

![image](https://user-images.githubusercontent.com/17878953/225955492-211afd53-17ef-4a9b-845f-1746ea3e8f92.png)

![image](https://user-images.githubusercontent.com/17878953/225955261-0e09a1d5-492c-4dc9-8c85-c32b5eb5efde.png)



(2) I also saw how easy it is to set up preset decision rules in the example config. I did notice something else we may want to address in this PR: when I tried to set I set my own decision rules for the default config...

![image](https://user-images.githubusercontent.com/17878953/225958142-a8908415-3cee-43ae-bba1-827709c45762.png)

And then I later decide to add decision rules for the two categories I left out, I noticed they default to their fourths. Is there anyway we could make those categories disburse evenly over the range slider that wasn't accounted for in the config file? If I wasn't paying attention, I would have missed .2 to .25 and .75 to .8.

![image](https://user-images.githubusercontent.com/17878953/225961870-5c453b04-a4f1-4123-bd79-f2d8aeea4c40.png)





(3) Also, I tried to test with only two categories, and it didn't work either. See error message below. It seems the "minus 2" when selecting a color palette is hurting us. I could see an org wanting to only have a "keep" or "discard" categories (or "compliant" / "not compliant" or Go/No Go, etc).. Honestly, I could see a company just wanting to use one category.

![image](https://user-images.githubusercontent.com/17878953/225958735-eaff9d80-7bd3-435c-a22b-7165f47b9cc4.png)

![image](https://user-images.githubusercontent.com/17878953/225959748-5a1b5182-6d33-444c-b0e4-de0bee0b2d0d.png)

(4) I know this PR is still draft, but there doesn't seem to be any protection when specifying strange presets for decision rules. For example:

![image](https://user-images.githubusercontent.com/17878953/225964454-6a6cd081-8a41-41be-9c5e-45da61ccd596.png)

OR

![image](https://user-images.githubusercontent.com/17878953/225965952-eff7c464-a3a5-44b9-ac7e-db9b4f7cc9f4.png)


Both results in borked range sliders. It looks like the ranges are still stored appropriately in the DT table though:

![image](https://user-images.githubusercontent.com/17878953/225963738-5442f795-bb12-424a-8707-9ab855ac7ac5.png)

And when you try to load a pkg when their is overlap in ranges however, you get this error:

![image](https://user-images.githubusercontent.com/17878953/225966270-baac7bfb-5507-41b2-86ee-b3290d00f6da.png)

In addition, it doesn't handle categories that share the same name well. This action would have to be stopped:

![image](https://user-images.githubusercontent.com/17878953/225968978-1273c947-681f-432c-9378-7104481cccec.png)

![image](https://user-images.githubusercontent.com/17878953/225969098-3ea7f831-ced1-487c-a40a-12d70196af7b.png)


So, in summary, we may need a way to provide helpful informative error messaging to the console. Plus the documentation would help.


(5) Along the lines of naming the categories, consider this example. I don't think we should orient the app in such a way that assume the suffix of "risk" makes sense. Yes, the decision is "risk-based", but the decision could reflect what the user hopes to do with that info. With the following example:

![image](https://user-images.githubusercontent.com/17878953/225967168-e3cd3056-bde3-468a-9b4e-9bef4274e284.png)

We should remove the word risk here. If the user wants to display the word "risk" they should include it into the config file. It looks like the config file handles decision categories that are multiple words quite well.
![image](https://user-images.githubusercontent.com/17878953/225966930-8d3a356d-85e5-4de1-93ac-8631aab8d721.png)

However, I noticed that we'll need to change the label on this slider (below) to be "Select Package Decision". Also, we might need to add some padding on the left and right as the text was going off screen.

![image](https://user-images.githubusercontent.com/17878953/225967915-8787420f-9e93-4096-9a4c-cefa266aea5d.png)

(6) thinking more about the example directly above, perhaps we need to give the user an opportunity to change the default colors around manually. For example, if they feel the "needs review" category/tag isn't really on the same risk gradient/spectrum, perhaps they'd want to change the color to grey or something. Would it be possible to insert a collapsible color picker into the Admin Tools tab? I'd think you'd want your ADMIN users to have access to this after the app is deployed so perhaps it doesn't belong in the config file? Or perhaps you can set defaults in the config, but the admin can change those values, and it could get stored in the db?

Phew, that's enough for now. In summary - this PR is top notch and I love where it's going. Nice work!

2023-03-20 13:16 UTC, AARON-CLARK commented
Just a loose thought - I did not test what happens when the user changes the auto-decision thresholds during a session. Do the new thresholds get overwritten in the config file? or does it get stored in the `database.sqlite` file and those will get used over the config file, if they exist?

2023-03-20 14:18 UTC, Jeff-Thompson12 commented
> Just a loose thought - I did not test what happens when the user changes the auto-decision thresholds during a session. Do the new thresholds get overwritten in the config file? or does it get stored in the `database.sqlite` file and those will get used over the config file, if they exist?

@AARON-CLARK It does not change the configuration file. My thoughts were that the configuration file was mostly meant to setup the application on initialization. This also allows it to be shared across projects. You can easily use the same credential and/or decision rules for multiple initializations.

This is also why I added the decision rules to the database itself. Any changes to the rules after initialization should be tracked with that project and shouldn't change configurations for other projects.

2023-03-20 15:39 UTC, AARON-CLARK commented
Another thought I had while writing the 'deployments' vignette today:

https://github.com/pharmaR/riskassessment/blob/433ecc9a76a1d5ef582b6f6542b83ef589dbb478/vignettes/Deployment.Rmd#L65

If you read that paragraph, you'll recall that we currently initialize weights using [initialize_metric_table.sql](https://github.com/pharmaR/riskassessment/blob/master/inst/app/www/sql_queries/initialize_metric_table.sql) file to update the `metric` table. Perhaps we should be initializing those in the config file. Thoughts?

2023-03-20 19:32 UTC, Jeff-Thompson12 commented
> Perhaps we should be initializing those in the config file. Thoughts?

I think that's a good direction to head. Moving some of these items to configurations with defaults.

2023-03-21 13:01 UTC, Jeff-Thompson12 commented on R/mod_decision_automation.R
> +    auto_db <- process_dec_tbl()
I have done some minor variable renaming. Take a look and let me know what you think.

2023-03-21 13:02 UTC, Jeff-Thompson12 commented on R/run_app.R
> +#' @param decision_categories a character vector of the decision categories
The unneeded parameters have been removed.

2023-03-21 13:02 UTC, Jeff-Thompson12 commented
Reorganizing the changes requested for better tracking...

- [ ] Rogue color in slider
> I edited the `sliders.css` file. If you restart the R session the rogue color will go away.

- [ ]  Fill remaining gaps between ranges not covered in config
> It is hard for me to envision how to implement something like this without a bunch of obtuse code that potentially slows down the initialization of the app. I don't really think this is necessary either since we do ask for verification of selected inputs. Of course if we think this would be a feature a user would be looking for, I can still work to implement it.

- [ ] Accommodate two categories or even just one
> This has been added now.

- [ ] We need config file error handling
> Some rudimentary checks have been implemented. Let me know if any situations seem to be missing.

- [ ] Re-naming
> I have removed the automatic "Risk" suffix added to the decision. This will allow initialization of non-Likert style decision categories. The decision automation may not make sense in those situations, but it need not be enabled either.

- [ ] Custom colors
> I agree that we should allow the user to assign their own colors (especially since we have a decision categories database table now), but I think that should be handled in a separate issue/PR.

2023-03-21 15:17 UTC, AARON-CLARK commented
> * [x]  Accommodate two categories or even just one
> 
> > This has been added now.

I just tested one category and this doesn't seem to be working yet. Optimally, we'd just swap out the `sliderInput()` for a `shinyWidgets::materialswitch()`

![image](https://user-images.githubusercontent.com/17878953/226652259-64272ba0-52d0-4e18-ba2c-08cdafcbd9db.png)

2023-03-21 15:19 UTC, AARON-CLARK commented
Whoops!

2023-03-21 15:26 UTC, AARON-CLARK commented
> * [ ]   Fill remaining gaps between ranges not covered in config
> 
> > It is hard for me to envision how to implement something like this without a bunch of obtuse code that potentially slows down the initialization of the app. I don't really think this is necessary either since we do ask for verification of selected inputs. Of course if we think this would be a feature a user would be looking for, I can still work to implement it.

In this example, I create some presets of [0,.1] and [.5,1]. When clicking to add "Medium", the range that appears just seems really odd. Haha, I think people will be really confused. But if you think my suggestion will negatively impact the app, then I'm willing to live with it. No biggie.

![image](https://user-images.githubusercontent.com/17878953/226650645-c1369150-f86a-4124-af88-c419fcdebc16.png)

2023-03-24 02:08 UTC, AARON-CLARK requested changes
Something seems to be broken. I restarted my session, deleted the `database.sqlite` file, and re-ran with this config file:

![image](https://user-images.githubusercontent.com/17878953/227405544-a75abefa-c6c8-4dc2-b2eb-209c4c3bd088.png)

But the sliders came out like below. Can you replicate it?

![image](https://user-images.githubusercontent.com/17878953/227405633-aa0943ae-26ab-4c22-b0f3-599e035f0909.png)

The table came out just fine:

![image](https://user-images.githubusercontent.com/17878953/227405720-56d0b4ec-83a4-432a-a8ed-1068795c0068.png)

2023-03-24 15:02 UTC, Jeff-Thompson12 commented
@AARON-CLARK The code I previously had should have worked. There is something going on in `{formattable}` when it parses the formatting functions. Making the color list a named function fixes the issue.

2023-03-24 20:28 UTC, AARON-CLARK approved these changes
💪🏼

2023-03-24 20:29 UTC, merged