Store assessments for rescoring
pharmaR/riskassessment pull request #537
Opened 2023-06-08 20:08 UTC by Jeff-Thompson12

Addresses #536 

Stores the assessment tibble/metrics as bits so that the app can pull them back from the database to rescore without reassessing.

2023-06-09 12:34 UTC, Jeff-Thompson12 commented
@AARON-CLARK not really a new feature but thought you might want a look anyways.

2023-06-12 13:12 UTC, AARON-CLARK requested changes
Ahhhhh, the re-scoring process was SO much faster. Much needed! Thank you @Jeff-Thompson12! It's kind of a new feature, right? Could you please update the `NEWS` file and increment the dev version?

Also, I've been noticing this new "No encoding supplied" message that I think comes from the new version of `riskmetric`. Have you noticed it? I'm not sure what the warning is about regarding uploading the `samplesizeCMH` package, but it seemed to work just fine in the app.

![image](https://github.com/pharmaR/riskassessment/assets/17878953/b8d52b51-89f5-4857-9f81-5fdcec9b84e7)

2023-06-12 13:15 UTC, Jeff-Thompson12 commented
> Also, I've been noticing this new "No encoding supplied" message that I think comes from the new version of `riskmetric`. Have you noticed it? I'm not sure what the warning is about regarding uploading the `samplesizeCMH` package, but it seemed to work just fine in the app.
> 
> ![image](https://user-images.githubusercontent.com/17878953/245154133-b8d52b51-89f5-4857-9f81-5fdcec9b84e7.png)

Yes, I have noticed and it is related to `riskmetric`. I have not looked into it beyond that though.

2023-06-12 13:43 UTC, Jeff-Thompson12 commented on R/utils_insert_db.R
> +dbUpdate <- function(command, db_name = golem::get_golem_options('assessment_db_name'), .envir = parent.frame(), params = NULL){
> And not your fault, but maybe fix the "Environment" spelling error in `@param .envir Environemtn to evaluate each expression in`

That's where you are probably wrong. It's just not my fault with regards to this PR.

2023-06-12 13:58 UTC, Jeff-Thompson12 commented on R/utils_insert_db.R
> +      params = list(pkg_assess = assessment_serialized[metric$name,])
This was a fun PR. I have never used the BLOB data type in SQL before. At first I was going to trying using `dput()`, but I felt like we could run into weird behavior with storing and evaluating strings like that. Then I came across a blog post that used this method to store information related to a graph and realized that this should solve our issue with reproducibility which is why we reassessed in the first place.

2023-06-12 14:35 UTC, AARON-CLARK commented on R/utils_insert_db.R
> +      params = list(pkg_assess = assessment_serialized[metric$name,])
I've never seen the BLOB either! How neat is that?

2023-06-12 14:37 UTC, AARON-CLARK approved these changes
Off the ⛓️

2023-06-12 14:37 UTC, merged