Add Explore Metrics button to uploadPackages tab
pharmaR/riskassessment pull request #658
Opened 2023-10-16 12:29 UTC by Robert-Krajcik

closes #653

2023-10-16 16:20 UTC, AARON-CLARK requested changes
Hi @Robert-Krajcik, this PR is close. I noticed that when I upload a packages initially, the button works. However, if I upload another package afterwards, the button doesn't work anymore. Can this be resolved?

2023-10-16 16:20 UTC, AARON-CLARK commented on NEWS.md
> +* Add Explore Metrics button from Upload Packages tab (#653)
```suggestion
* Add "Explore Metrics" button to Uploaded Pkgs Summary tab on Upload Packages tab (#653)
```

2023-10-17 12:44 UTC, Robert-Krajcik commented
Hi @AARON-CLARK 
`I noticed that when I upload a packages initially, the button works. However, if I upload another package afterwards, the button doesn't work anymore. `
I am not able to replicate this.  Seems to work for me.  Maybe you should share your screen with me later today?

2023-10-17 15:35 UTC, Robert-Krajcik commented
Hi @AARON-CLARK 
This is working now for me.

2023-10-17 15:46 UTC, AARON-CLARK approved these changes
👍🏼 👍🏼 👍🏼

2023-10-17 15:46 UTC, merged