Autonavigation
pharmaR/riskassessment pull request #779
Opened 2024-05-14 16:41 UTC by narayanan-iyer-pfizer

This addresses #644  and  adds new buttons

2024-05-14 19:55 UTC, jthompson-arcus requested changes
@narayanan-iyer-pfizer thanks for working on this. The feature is not working for me. Didn't dig too deep into why that was the case. The JavaScript does not appear to be functioning as intended though.

I'm not a huge fan of how the buttons look. I think personally I would want something more minimal. Could a count also be included (e.g. < 1 of 3 >)? I think that would add a lot.

2024-05-14 19:55 UTC, jthompson-arcus commented on R/mod_code_explorer.R
> +                    var $index =Array.from($highlights_list).findIndex(node => node.isEqualNode($curr_sel));
This line appears to not be working.

2024-06-11 17:42 UTC, narayanan-iyer-pfizer commented on R/mod_code_explorer.R
> +                    var $index =Array.from($highlights_list).findIndex(node => node.isEqualNode($curr_sel));
fixed and count added

2024-06-12 12:39 UTC, jthompson-arcus commented
@narayanan-iyer-pfizer I started looking at this again and then realized you didn't re-request me to review. Did you want a review or are you still working?

2024-06-12 12:41 UTC, narayanan-iyer-pfizer commented
> @narayanan-iyer-pfizer I started looking at this again and then realized you didn't re-request me to review. Did you want a review or are you still working?

Please review it. I'm done with this

2024-07-03 17:20 UTC, jthompson-arcus requested changes
@narayanan-iyer-pfizer sorry for sitting on this review for so long. 

In addition to the conversations below, I noticed that if you select the file type "Help Documentation" that the buttons stay visible for the last view.
![image width="100%"](https://github.com/pharmaR/riskassessment/assets/160783290/b2f7d363-b142-4488-9371-467c82b00bd1)

2024-07-08 11:27 UTC, narayanan-iyer-pfizer commented on R/mod_code_explorer.R
>            fluidRow(
done

2024-07-08 12:38 UTC, merged