Highlight individual contributors more than orgs on `About` tab
pharmaR/riskassessment pull request #780
Opened 2024-05-15 19:43 UTC by aclark02-arcus

Fixes #778

2024-05-16 16:51 UTC, jthompson-arcus requested changes
I think also if we have some standardized dimensions (or even aspect ratio) to the photos, then we will be able to more easily get the two rows of cards to have the same height. Either way that will help us with formatting.

2024-05-16 16:51 UTC, jthompson-arcus commented on NAMESPACE
> +import(shiny)
We don't want to import all of shiny.

2024-05-16 16:51 UTC, jthompson-arcus commented on R/mod_aboutInfo_utils.R
> +#' @import shiny
This is the offensive line that imports all of shiny.

2024-05-16 16:51 UTC, jthompson-arcus commented on R/mod_aboutInfo_utils.R
> +        file = pic,
```suggestion
        file = NULL,
        src = pic,
```
Currently, you have these photos bundled into the application itself, which I think means we want to point to their source directly using the suggestion above. Why do both?

2024-05-16 16:51 UTC, jthompson-arcus commented on R/mod_aboutInfo_utils.R
> +      fillable = TRUE,
```suggestion
      fillable = FALSE,
```
This will keep the photos from getting stretched out.

2024-05-16 16:51 UTC, jthompson-arcus commented on R/mod_aboutInfo_utils.R
> +      pic = file.path('inst/app/www/images',photo_file),
```suggestion
      pic = file.path('www/images',photo_file),
```
If we make the change above to point directly to source, we need to make this change as well.

2024-05-16 16:58 UTC, jthompson-arcus commented on R/mod_aboutInfo_utils.R
> +      fillable = TRUE,
We could also probably leave this be if we standardize the size/ratio of the photos.

2024-05-17 14:00 UTC, aclark02-arcus commented
Thanks for all the suggestions @jthompson-arcus, I was able to incorporate them all and add a few more changes. Below is what is rendered now. I basically realized that all our GitHub sources for pics were squares, so I decided to stay with the square theme throughout.

![image](https://github.com/pharmaR/riskassessment/assets/162465159/63904c62-738c-4a2f-8d0f-2f68891a2281)

A couple of things that are still out of sorts:

- looks like we lost the center-justified-items class, but this doesn't look terrible left justified
- the target = "_blank" stuff still isn't working

2024-05-17 14:05 UTC, jthompson-arcus commented on R/mod_aboutInfo_utils.R
> +      ),
```suggestion
        href = ifelse(is.na(site) | is.null(site), 'https://www.pharmar.org', site)
      ) |>
        tagAppendAttributes(target = "_blank", .cssSelector = "a"),
```
This fixes the target for the URLs.

2024-05-20 16:36 UTC, jthompson-arcus commented on dev/001_start.R
> +usethis::use_package("png", type = "Suggests")
I noticed that this is "added" to the project but not `renv.lock`. I'm assuming you used it to resize the pictures. Perhaps we should ignore the `dev/` folder with regards to `renv`.

2024-05-20 16:38 UTC, jthompson-arcus commented on tests/testthat/test-contrib_card_utils.R
> +  if(rlang::is_installed("png")) {
I see that `png` is used here. Should be added to `renv.lock`.

2024-05-20 16:40 UTC, jthompson-arcus requested changes
@aclark02-arcus I think the cards are looking really good now. Looks like the package `png` needs to be added to the R environment for the test, but other than that I'm satisfied.

Want to change it from draft? Or do you have other changes you want to make?

2024-05-20 20:35 UTC, jthompson-arcus approved these changes
LGTM

2024-05-20 20:35 UTC, merged