Rel `v3.1.0` Prep
pharmaR/riskassessment pull request #795
Opened 2024-06-17 19:24 UTC by aclark02-arcus

Prepping for a new minor release

2024-06-17 20:29 UTC, jthompson-arcus requested changes
In addition to the notes below. I noticed that we have no mention of updating the R version and our PPM snapshot date. Should probably add a note about that under the "For Devs" section.

2024-06-17 20:29 UTC, jthompson-arcus commented on NEWS.md
> +* Drastically shorten waiting time in `Code explorer`/ `Package explorer` by reading tarballs in memory (#707)
```suggestion
* Drastically shortened waiting time in `Code explorer`/ `Package explorer` by reading tarballs in memory (#707)
```

2024-06-17 20:29 UTC, jthompson-arcus commented on NEWS.md
> +* Move package upload process to a function, allowing devs to populate the database outside of the application
```suggestion
* Moved package upload process to a function, allowing devs to populate the database outside of the application
```

2024-06-17 20:29 UTC, jthompson-arcus commented on NEWS.md
> +* Utilize `{archive}` to parse DESCRIPTION file, increasing speed in package upload process
```suggestion
* Utilized `{archive}` to parse DESCRIPTION file, increasing speed in package upload process
```

2024-06-17 20:29 UTC, jthompson-arcus commented on NEWS.md
> +* Utilize `{archive}` to parse DESCRIPTION file, increasing speed in package upload process
This also seems more like a user enhancement to me.

2024-06-17 20:29 UTC, jthompson-arcus commented on NEWS.md
> +* updated manifest file and deployments article
```suggestion
* Updated manifest file and deployments article
```

2024-06-18 13:09 UTC, aclark02-arcus commented
@jthompson-arcus, I made the changes you suggested. I just requesting your review to re-trigger the manifest build. Will merge when that commit is added.

2024-06-18 13:10 UTC, merged